language: node_js
sudo: false
node_js:
  - 10
install:
  - npm install
env:
  - NODE_ENV=test
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: p8Igjzx0ri0/pPDvmw2+8YCxRY2yp+bf51F+ofCfSsaI/AaIZYacX8Op2CfnzMKgFFV9nkVI5ID6P9/dFCSqgsG8RxP7R63QbMYqfk0S4oEiUav6n3G/XZQP7vYkKYy9hQp3JpF5KakeOcxEY/4lrCCBzz60tP8e1dhd/QmsU4gdjDVffZ3eneeQTy8TiSUKbrSfXln3vBN0QcflYRIoufzIoIiNOQ6WnCU/p7RUM0p0QZHRvIrGfDsnUx31gK4crbuHOxdLIDZ6CplCMEiFXvRb5FTFeFwAvyKv65XAqPq+wLcX57mFMU3j7K3iddZGlUqO7NeUYNE0Iy6Kl8iSWXk/dqhAvvAnxpbbzYaF6xAZ4fQ9jj8gsaZkBEqs+W8VAtwFjkvCGuyAKDkRJ7rxrbyvjb2CjvlRBtu5e03nWAk8QBFQJI032c/DtTL/5S671qZ/qyXpQTpHTMtiZrZ+P5Pl9Rn0BLKLsF8APOZK0f3sratYGjS1xjt4jrWPfu9hzQUNzNl3rjN9DeYiHNTm0KCzqsQ7CtOkEmNDJUAxqmHh1Nvjk+Oj2O2QKpLVnnbMUcaBFuZ6pVBmyu6uboatSskovi7lBZk4z26AXpIdS2ip7NnhbKXYerLGs1OfH2i7jHIz5zC3Y23XiLbgGipej2k6gidTb2SEypJVt2IaIpE=
  - secure: BQeH5oWIdkDQvfMZg4djRIgPqeGR4sLDSpPUpk7UdMP9A0N1z5AoBDOi+4jUQJEQT0+Z0eJU/jh81ShOIotJR4hJ3DlNkXKbFckF9CD5zP2L1/lTMeX75zqwMzBMTQKFOMrU9ToTLj6XpbPYrs81rjVMcPDnamx7jzlPc1DwdkNBiZpy19tSiXJCfjo7gk9efOdRk2DlJ2+fGDTmQqaZvhiyhc+LOqN2efzjN+2hp2d9fdeptsdiN3oOA56y9OqLqll4uKIWw/0Ju+JpzApnpCSnnNQc0TaA+sNsU+K6FislseIsMV2g53kBRPq3P1g8TDuuhHlAsZY9kgmwyg1Kc60FWAhNkYSIqT98N1GR8oGlN1/bUSoQhrZi6/BTtemCvq6KfXDnmiTuUJc7dJRJVXMssMD7xLCfYXM7sOfLvs1NcEdCbhFPVj4GbLacGHXdiBS1gXGylwFatb4U3EKk5LSdPQqDlwxYpgY5uKlToEESC1YMElpUWcF0ecQLtM06k1REVY4SxRSoeOsR+4aaRCY9dDoKJda7baLWDl2tKN8pBUhyklAy8LstouRDwLJhmy+tDjtEuLNhGkZBf/FuXUsgSKmSUyzI07Lzow7dUPsgWEgCXIU8RZwU6k1BVbuKkM9jpnhdcQ74SkKuRsTd2lwb8M4UjsZxyx3PbTxD1zA=
script:
  - npm run codecov
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - export REPO=podshows/podcloud-rss
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
    ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
before_deploy:
  - openssl aes-256-cbc -K $encrypted_60b4ecdad46d_key -iv $encrypted_60b4ecdad46d_iv
    -in .deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - ssh-keyscan barry.podshows.fr >> ~/.ssh/known_hosts
deploy:
  - provider: script
    script: "./deploy.sh"
    on:
      branch: master
