language: node_js
sudo: false
node_js:
  - 10
install:
  - npm install
env:
  global:
      - secure: "fFicGvD1cED3J63OZL969ExHakNBDGS11CyGJSlnv1W+ZD2hKOYVR0L6+Y4SO5J+tssY8mOGmOIh0hfifiUpPfcKyK+oQG4SOowt3G0YmDxudLKOYlfUueCZVEIsT3M2+j+/8Jshz5SOj8WNtsOyLPpnpYJM5lA0XzbZx/dU5tvjjVkkQQ82NJwzD7wQbfqyXpkYkHWArOvImo8evH7r2/tzFGx48JlI5ZYiVLPhFIknV2URseSOaMr3F/uixOFOEOtH90uYn+BCT7iJ9wpFBI9vo6R8oYoCRwi+R9zfP1E9NmZGIC8H8v23TSn5oPHar+C1a4G0xx/JzXBnfABfBsTZtMI4J1YIn4gM1GZ3M6GQ7S+FCbZxSBgTfMbdYkG5W6Is7GllBme/Z7Usjw/jxYoKQ7DMzuN2ikQW3q3Z2vI4+p6rtMovxekjjKWsE0Dzk6CrPfgZ7Hu8KWG+qWlkLvVYhA/7mM0pAwRxgx/dQi477BFwSWppLRXrSbVA4aYdV/1D6R4o+I0Q2YDO1fdKXJ4IAfH+FkqXmuvFJVb531/3onP0dJnqq7Pzhtzc/DBH/XP+NirdpujNRibR+WmGGOWf8iv75r4R7qpNMHQl6GZZmoxnAL0KjQQlbNhjGtC2n2AoHEvD3OUdcrrWnRjjiVPH0CVpU2YwSsGN5OgRb1c="
      - secure: "bMJ6dG2R+3UkkO2KD5mHXaPqVkDoUhkZioS0+9CL06KH3cXrsYktG4QWWG7lHrq+qH2wOyclB6KzDtQmfdwviVpZdKxTXx4px18Do0yOeErR7nvf/Ok/x9br+b07yurRkSSqAFGjucPHIbsne5jNO3A6aTQY+eHfvA04jLmwWsi5j40ZTN1Mj4kUpln9Nj3X7Th+uj9Fr5q3OccDUttldSP6QWwLP/CbZrzzJZDLok5eNeC23pFyLOWsmGUk1wRLGMhEBn/RErbNx0n3tDAumAvStm6ANoHNHuCdDoa/6/S/dwi97bLx2Vp9ylXt0GkXsaCqcmfyo1PbPaGCv7tCEaHKhkxzIth76imdiHhvJ+g1SlhYDIAR/O4fOVdxLI4mR9flzcRgKvR5Mkzb5QIGiv0mehQlob+nGBYmD8pLv5zBXinbhuE8G3tTXnfAoSfqWJ+h3JPOZg9Mbm8BcYR28mmM0NFYk17PQUM6KOqj0n3ukD6R+5PK34zk8VcHVuX1F1W4C+QOjSJJIdPqQQctb1jma/LLJbkPUFDT/nT0GCvg8bMSabtm78D5etY6UK/QIDeAXuDhfacyE6ePYrtW2LtAKY39/NGUf7Zu+4XIfxV3+l8nYTOdRvRWC3K8KS5VYs4g/NSDX4TDXfFxTQyi5PM8Wr6N4rAA9aX01dv8UHE="
      - NODE_ENV=test
      - COMMIT=${TRAVIS_COMMIT::8}
script:
  - npm run codecov
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - export REPO=podshows/podcloud-rss
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
    ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
before_deploy:
  - openssl aes-256-cbc -K $encrypted_60b4ecdad46d_key -iv $encrypted_60b4ecdad46d_iv
    -in .deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - ssh-keyscan barry.podshows.fr >> ~/.ssh/known_hosts
deploy:
  - provider: script
    script: "./deploy.sh"
    on:
      branch: master
