language: node_js
sudo: false

node_js:
  - 10

install:
  - npm install

env:
  - NODE_ENV=test

script:
  - npm run codecov

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
- export REPO=podshows/podcloud-rss
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO

before_deploy:
  - openssl aes-256-cbc -K $encrypted_60b4ecdad46d_key -iv $encrypted_60b4ecdad46d_iv
    -in .deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - ssh-keyscan barry.podshows.fr >> ~/.ssh/known_hosts

deploy:
  - provider: script
    script: "./deploy.sh"
    on:
      branch: master
