# project_name=podcloud-rss
version: "3.4"
services:
  rss:
    image: "podcloud-rss"
    build:
      context: .
      target: runner
    volumes:
      - .:/usr/src/app
      - ~/.docker/traefik/ca/cert.pem:/ca.crt
    networks:
      - traefik
      - default
      - podcloud
    environment:
        NODE_EXTRA_CA_CERTS: /ca.crt
        NODE_TLS_REJECT_UNAUTHORIZED: 0
    extra_hosts:
      - "dave:192.168.10.40"
    labels:
      traefik.frontend.rule: "HostRegexp:{subdomain:.*}{host:podcloud|lepodcast}.test;Path:/rss"
      traefik.frontend.priority: 900

  rss-feed-cache:
    image: redis
    command: ["redis-server", "--maxmemory 1gb", "--maxmemory-policy allkeys-lfu"]
    networks:
      - default

  rss-ping-cache:
    image: redis
    command: ["redis-server", "--maxmemory 1gb", "--maxmemory-policy allkeys-lru"]
    networks:
      - default

networks:
  podcloud:
    external: true
  traefik:
    external: true
