# project_name=podcloud-rss
version: "3"
services:
  rss: # scale=5
    image: podshows/podcloud-rss:latest
    networks:
      - traefik
      - default
      - podcloud
    volumes:
      - ./config:/usr/src/app/config
    env_file:
      - ./.env.local
    restart: always
    labels:
      traefik.enable: true
      traefik.backend: "podcloud-rss"
      traefik.frontend.rule: "HostRegexp:{subdomain:.*}{host:podcloud|lepodcast}.fr;Path:/rss"
      traefik.frontend.priority: 900

  rss-feed-cache:
    image: redis
    command: ["redis-server", "--maxmemory 4gb", "--maxmemory-policy allkeys-lfu"]
    restart: always
    networks:
      - default

networks:
  podcloud:
    external: true
  traefik:
    external: true
